name: CI/CD Pipeline
on:
 push:
   branches:
     - main
 pull_request:
   branches:
     - main
env:
 IMAGE_NAME: my-docker-app
 IMAGE_TAG: latest
 DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
 DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
 SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
    # - name: Checkout Code
     #  uses: actions/checkout@v3
    # - name: SonarQube Code Analysis
     #  uses: sonarsource/sonarqube-scan-action@master
     #  env:
       #  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # SONAR_HOST_URL: "https://sonarcloud.io"
     - name: Docker Login
       run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
     - name: Build and Push Docker Image
       run: |
         docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG .
         docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG
     - name: Deploy to Minikube
       run: |
         kubectl apply -f k8s/deployment.yaml
         kubectl apply -f k8s/service.yaml
     - name: Notify on Failure
       if: failure()
       run: echo "Deployment failed!"
